# Generated by Django 3.0.3 on 2020-03-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Assignkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userword', models.CharField(max_length=25)),
                ('keyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qbuilder.keyword')),
            ],
        ),
    ]
